# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - readme.md
      - .gitignore
      - api.md
      - Dockerfile
      - .dockerignore

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo chmod +x gradlew
  displayName: Pre-build
- task: Gradle@3
  displayName: Build artifact
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'bootJar'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false

- script: |
    sudo cp build/libs/*.jar $(Build.ArtifactStagingDirectory)
  displayName: Pre-upload

- task: PublishBuildArtifacts@1
  displayName: Upload artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'EveryPush.Server'
    publishLocation: 'Container'

