spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/push_server?serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8091
