spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/push_server?serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
  jpa:
    # MySQL8Dialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8091